- name: Hello World
  hosts: local
  connection: local
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello, World!"


- name: paly-2
  hosts: local
  connection: local
  tasks:
    - name: play-2 and task-1
      ansible.builtin.debug:
        msg: "Hello From Play-2 and Task-1"