- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140 Hrs"
    TRAINER: "Siva Kumar Reddy"
  tasks:
    - name: Print the play level variable
      vars:
        COURSE: "Ansible for DevOps"
        DURATION: "10 Hrs"
        TRAINER: "Siva Kumar"
      ansible.builtin.debug:
        msg: "Course is: {{ COURSE }}"