- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names 
    ansible.builtin.debug:
      msg: "Hello, {{ item }}"
    loop:
      - Alice
      - Bob
      - Charlie
      - Durga
      - Gunji
      - 1431
      - - 3.14159
