- name: Demo on filters
  hosts: local
  connection: local
  gather_facts: false

  tasks:
    - name: Greeting
      ansible.builtin.debug:
        msg: "Hi Durga Gunji, {{ GREETING | default('Good Morning') }}"